services:
  - type: web
    name: doctorcare-api
    env: node
    region: oregon
    plan: free
    buildCommand: "npm install"
    startCommand: "npm start"
    envVars:
      - key: TWO_FACTOR_API_KEY
        sync: false
      - key: EMAIL_USER
        sync: false
      - key: EMAIL_PASS
        sync: false
